name: kitten-in-armour-bot

services:
  kitten-in-armour-bot:
    container_name: kitten-in-armour-bot
    image: ghcr.io/mittaan/kitten-in-armour-bot-kitten-in-armour-bot:latest
    environment:
      GETIMG_API_KEY: ${GETIMG_API_KEY}
      BOT_TOKEN: ${BOT_TOKEN}
      MEGA_EMAIL: ${MEGA_EMAIL}
      MEGA_PASSWORD: ${MEGA_PASSWORD}