name: publish

on:
    push:
        branches: ['master']

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.actor }}/kitten-in-armour-bot-kitten-in-armour-bot:latest

jobs:
    pull:
        name: pull changes
        runs-on: ubuntu-latest

        steps:
            - name: Get changes
              uses: appleboy/ssh-action@v1.1.0
              env:
                WORKDIR: ${{ secrets.WORKDIR }}
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: 22
                envs: WORKDIR
                script: |
                  cd $WORKDIR
                  git checkout master
                  git pull

    publish:
        needs: pull
        name: publish image
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: login
              run: |
                echo ${{ secrets.GH_SECRET }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            - name: Build and Publish
              run: |
                docker build . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    deploy:
        needs: publish
        name: deploy image
        runs-on: ubuntu-latest

        steps:
            - name: install ssh keys
              run: |
                install -m 600 -D /dev/null ~/.ssh/id_rsa
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
            - name: connect and pull
              run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORKDIR }} && docker compose pull && docker compose up -d && exit"
            - name: cleanup
              run: rm -rf ~/.ssh